### ISSUE TITLE
invalid Peer was used

### ISSUE THREAD

**Issue by yoburtu** [filippz/telegram_import#11]
Hi, thanks for your script. Whe I exec it I have this error:

```
$ python3 telegram_import.py --path ChatExport_2024-08-29 --peer "myphonenumber" --test_only
Loading config.ini
Loading result.json
Converting format
Traceback (most recent call last):
  File "/home/pepus/git/telegram_import/telegram_import.py", line 249, in <module>
    import_history(
  File "/home/pepus/git/telegram_import/telegram_import.py", line 198, in import_history
    client(functions.messages.CheckHistoryImportPeerRequest(
  File "/home/pepus/.local/lib/python3.12/site-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/pepus/.local/lib/python3.12/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pepus/.local/lib/python3.12/site-packages/telethon/client/users.py", line 87, in _call
    result = await future
             ^^^^^^^^^^^^
telethon.errors.rpcerrorlist.PeerIdInvalidError: An invalid Peer was used. Make sure to pass the right peer type and that the value is valid (for instance, bots cannot start conversations) (caused by CheckHistoryImportPeerRequest)

```
How can I fix it?. Is peer my Telegram phone number?.

Best regards.

**Comment by yoburtu** [comment]
Hi,I was using the peer of my own phone number. Now I tried with a different phone and it worked.

But the data was imported into the personal conversation with the other phone number.

One question, could the data be imported into a specific Telegram group?.

Regards.

**Comment by filippz** [comment]
> could the data be imported into a specific Telegram group

Yes - you should be able to use join link of the group for `--peer` parameter. Some limitations about group import still apply - for more info please take look at https://github.com/filippz/telegram_import/issues/9#issuecomment-2237146755

**Comment by yoburtu** [comment]
I don't quite understand, what would be the syntax for the --peer parameter?. The group is a private supergroup.

I have tried to put the group id, but it doesn't work:

```
$ python3 telegram_import.py --path ChatExport_2024-08-29 --peer "-1234567890"
Loading config.ini
Loading result.json
Converting format
Traceback (most recent call last):
  File "/home/pepus/git/telegram_import/telegram_import.py", line 249, in <module>
    import_history(
  File "/home/pepus/git/telegram_import/telegram_import.py", line 198, in import_history
    client(functions.messages.CheckHistoryImportPeerRequest(
  File "/home/pepus/.local/lib/python3.12/site-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/pepus/.local/lib/python3.12/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pepus/.local/lib/python3.12/site-packages/telethon/client/users.py", line 43, in _call
    await r.resolve(self, utils)
  File "/home/pepus/.local/lib/python3.12/site-packages/telethon/tl/functions/messages.py", line 218, in resolve
    self.peer = utils.get_input_peer(await client.get_input_entity(self.peer))
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pepus/.local/lib/python3.12/site-packages/telethon/client/users.py", line 439, in get_input_entity
    await self._get_entity_from_string(peer))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pepus/.local/lib/python3.12/site-packages/telethon/client/users.py", line 576, in _get_entity_from_string
    raise ValueError(
ValueError: Cannot find any entity corresponding to "-1234567890"
```

**Comment by filippz** [comment]
As noted for `--peer` I was able to use actual join link (for example _https://t.me/abc_DEF_1_) or just the last part of the link (for example _abc_DEF_1_). Also I haven't use quotes for `--peer` so you could/should probably omit them.

**Comment by yoburtu** [comment]
Hi, yes, I have tested with join link and works fine!. Thanks you very much.

Is there a limit on the size of the import? I need to import about 2.5 GB of history to a group, with conversations, videos, photos, stickers, and documents.

Best regards.

**Comment by filippz** [comment]
> Is there a limit on the size of the import

Not that I'm aware of. Please be advised that we're actually using native Telegram import so there could be some (even undocumented) limits: https://telegram.org/blog/move-history & https://core.telegram.org/api/import
AFAIK Telegram will throttle down the upload speed in order to prevent their "unlimited" storage from being misused so your import might just take a bit longer.

**Comment by yoburtu** [comment]
I have done a first test and it has not worked. The first image gave me an error, :-(: 

$ python3 telegram_import.py --path Family-ChatExport_2024-08-29 --peer "join link"
Loading config.ini
Loading result.json
Converting format
Starting import
Upload files mentioned in messages
Uploading IMG-20141125-WA0005.jpg:   0%|                                             | 6/8846 [00:01<32:20,  4.56it/s]Request caused struct.error: required argument is not an integer: UploadImportedMediaRequest(peer=InputPeerChannel(channel_id=2183249165, access_hash=689806442547844278), import_id=8078253785486435710, file_name='IMG-20141125-WA0005.jpg', media=InputMediaUploadedDocument(file=InputFile(id=1817390909054887887, parts=1, name='IMG-20141125-WA0005.jpg', md5_checksum='adba4bb7724d4fe2fc476acc90991ab0'), mime_type='image/jpeg', attributes=[DocumentAttributeImageSize(w=None, h=None)], nosound_video=None, force_file=None, spoiler=None, thumb=None, stickers=[], ttl_seconds=None))
required argument is not an integer
Uploading IMG-20141125-WA0005.jpg:   0%|                                             | 6/8846 [00:01<37:51,  3.89it/s]

This is the image format:

$ file Family-ChatExport_2024-08-29/files/IMG-20141125-WA0005.jpg
Family-ChatExport_2024-08-29/files/IMG-20141125-WA0005.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, Exif Standard: [TIFF image data, big-endian, direntries=2, orientation=upper-left], baseline, precision 8, 768x1024, components 3

Do you know what the problem could be?.

Thank you.

Regards.

**Comment by filippz** [comment]
> DocumentAttributeImageSize(w=None, h=None)

`w` and `h` shouldn't be `None`, but the actual width and height of the picture/image. Could you please send the json part from `result.json` for the IMG-20141125-WA0005.jpg so I can check what's going on. It seems that json doens't have width and height entries for that file.

**Comment by yoburtu** [comment]
This is the json part for the image:

{
   "id": -999983635,
   "type": "message",
   "date": "2014-11-25T21:37:42",
   "date_unixtime": "1416947862",
   "from": "User",
   "from_id": "user57441338",
   "file": "files/IMG-20141125-WA0005.jpg",
   "file_name": "IMG-20141125-WA0005.jpg",
   "thumbnail": "files/IMG-20141125-WA0005.jpg_thumb.jpg",
   "mime_type": "image/jpeg",
   "text": "",
   "text_entities": []
  },

That's!. Bye.

**Comment by yoburtu** [comment]
The problem perhaps is because the image is in files directory instead photos directory. And you had not foreseen that possibility..

**Comment by yoburtu** [comment]
That is, when that image was sent, it was sent as a document, rather than as an image. 

![Screenshot 2024-08-29 16-18-16](https://github.com/user-attachments/assets/3918e64b-50bf-4f99-b708-a06bbfc3d536)

**Comment by filippz** [comment]
Thanks for the json - it should work now, just download the new version. Let me know if it still fails.

**Comment by leokayser** [comment]
> As noted for `--peer` I was ableto use actual join link (for example _https://t.me/abc_DEF_1_) or just the last part of the link (for example _abc_DEF_1_). Also I haven't use quotes for `--peer` so you could/should probably omit them.

I ran into the same problem here. Using the invite link as the `peer` parameter does not resolve the error (group is a supergroup, the export is also from a supergroup).

```powershell
PS xxx\telegram_import> python .\telegram_import.py --path "xxx\Downloads\Telegram Desktop\testexport" --peer https://t.me/+invitelink
Loading config.ini
Loading result.json
Converting format
Starting import
Traceback (most recent call last):
  File "xxx\telegram_import\telegram_import.py", line 256, in <module>
    import_history(
  File "xxx\telegram_import\telegram_import.py", line 216, in import_history
    history_import = client(functions.messages.InitHistoryImportRequest(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "xxx\Python\Python312\Lib\site-packages\telethon\sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "xxx\Python\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "xxx\Python\Python312\Lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "xxx\Python\Python312\Lib\site-packages\telethon\client\users.py", line 92, in _call
    result = await future
             ^^^^^^^^^^^^
telethon.errors.rpcbaseerrors.BadRequestError: RPCError 400: IMPORT_PEER_TYPE_INVALID (caused by InitHistoryImportRequest)
```

In fact, using the group ID `-100XXXXXXXXXX` as `peer` **did solve the problem** for me.
